name: Web3 E2E tests

on:
  push:
    branches:
    - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - name: build
      run: |
        npm install
        npm run build-contracts
        npx spago build
      working-directory: test

    - name: test
      run: |
        docker run --rm -d -it -p 8545:8545 foamspace/cliquebait:latest
        sleep 2m
        npx spago test
      working-directory: test
