name: Run the solc test suite

on:
  push:
    branches:
    - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: run tests
      run: |
        npm install
        npx spago build -p solc
        npx spago test -p solc
